/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud-cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cloud Cover */
        get: operations["cloud_cover_api_cloud_cover_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cloud-cover/combined": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cloud Cover Combined */
        get: operations["cloud_cover_combined_api_cloud_cover_combined_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lightning": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lightning */
        get: operations["lightning_api_lightning_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/lightning-risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lightning Risk */
        get: operations["lightning_risk_api_lightning_risk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Purge Cache */
        delete: operations["purge_cache_api_cache_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CloudCoverResponse */
        CloudCoverResponse: {
            station: components["schemas"]["StationInfo"];
            /** Param */
            param: number;
            /** Resolution */
            resolution: string;
            /** Unit */
            unit: string;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
            /**
             * Attribution
             * @default Data: SMHI (CC BY 4.0)
             */
            attribution: string;
            /** Points */
            points: components["schemas"]["CloudPoint"][];
        };
        /**
         * CloudParam
         * @description Supported SMHI cloud parameters, as an integer enum so the query value
         *     is validated (422 on anything else) and surfaces as an int enum in OpenAPI.
         * @enum {integer}
         */
        CloudParam: 16 | 29 | 31 | 33 | 35;
        /** CloudPoint */
        CloudPoint: {
            /** Ts */
            ts: number;
            /** Value */
            value: number | null;
            /** Count */
            count: number;
        };
        /** CombinedCloudCoverResponse */
        CombinedCloudCoverResponse: {
            station: components["schemas"]["StationInfo"];
            /** Source Params */
            source_params: number[];
            /** Resolution */
            resolution: string;
            /** Unit */
            unit: string;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
            /**
             * Attribution
             * @default Data: SMHI (CC BY 4.0)
             */
            attribution: string;
            /** Points */
            points: components["schemas"]["CloudPoint"][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
        };
        /** LightningCenter */
        LightningCenter: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
        };
        /** LightningPoint */
        LightningPoint: {
            /** Ts */
            ts: number;
            /** Count */
            count: number;
        };
        /** LightningResponse */
        LightningResponse: {
            center: components["schemas"]["LightningCenter"];
            /** Radius Km */
            radius_km: number;
            /** Resolution */
            resolution: string;
            /**
             * Unit
             * @default strikes
             */
            unit: string;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
            /**
             * Attribution
             * @default Data: SMHI (CC BY 4.0)
             */
            attribution: string;
            /** Points */
            points: components["schemas"]["LightningPoint"][];
        };
        /**
         * LocationFactor
         * @description IEC 62305 location factor C_D. As a float enum the query value is
         *     validated (422 on anything else) and surfaces as an enum in OpenAPI.
         * @enum {number}
         */
        LocationFactor: 0.25 | 0.5 | 1 | 2;
        /** PurgeResponse */
        PurgeResponse: {
            /** Scope */
            scope: string;
            /** Deleted */
            deleted: {
                [key: string]: number;
            };
        };
        /** RiskResponse */
        RiskResponse: {
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Length M */
            length_m: number;
            /** Width M */
            width_m: number;
            /** Height M */
            height_m: number;
            /** Location Factor */
            location_factor: number;
            /** Line Length M */
            line_length_m?: number | null;
            /** N G */
            n_g: number;
            /** Radius Km */
            radius_km: number;
            /** Span Years */
            span_years: number;
            /** Ground Flash Count */
            ground_flash_count: number;
            /** Total Flash Count */
            total_flash_count: number;
            /** Collection Area Km2 */
            collection_area_km2: number;
            /** Expected Direct Per Year */
            expected_direct_per_year: number;
            /** Annual Probability */
            annual_probability: number;
            /** Return Period Years */
            return_period_years?: number | null;
            /** Expected Line Per Year */
            expected_line_per_year?: number | null;
            /** Hazard Band */
            hazard_band: string;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
            /**
             * Attribution
             * @default Data: SMHI (CC BY 4.0)
             */
            attribution: string;
        };
        /** StationInfo */
        StationInfo: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Distance Km */
            distance_km: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    cloud_cover_api_cloud_cover_get: {
        parameters: {
            query: {
                lat: number;
                lon: number;
                resolution?: "hourly" | "daily" | "monthly";
                param?: components["schemas"]["CloudParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CloudCoverResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cloud_cover_combined_api_cloud_cover_combined_get: {
        parameters: {
            query: {
                lat: number;
                lon: number;
                resolution?: "hourly" | "daily" | "monthly";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CombinedCloudCoverResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lightning_api_lightning_get: {
        parameters: {
            query: {
                lat: number;
                lon: number;
                resolution?: "hourly" | "daily" | "monthly";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LightningResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lightning_risk_api_lightning_risk_get: {
        parameters: {
            query: {
                lat: number;
                lon: number;
                length_m: number;
                width_m: number;
                height_m: number;
                location_factor?: components["schemas"]["LocationFactor"];
                line_length_m?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    purge_cache_api_cache_delete: {
        parameters: {
            query?: {
                scope?: "all" | "cloud" | "lightning";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PurgeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
